name: sea
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcrypt=4.4.28=h166bdaf_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.0=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - readline=8.2=h5eee18b_0
  - rust=1.82.0=h6a678d5_0
  - setuptools=75.8.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.2.2
      - antlr4-python3-runtime==4.8
      - attrs==25.3.0
      - beartype==0.22.8
      - bitarray==3.3.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.12
      - docopt==0.6.2
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - huggingface-hub==0.30.2
      - hydra-core==1.0.7
      - idna==3.10
      - jax==0.5.3
      - jaxlib==0.5.3
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - llvmlite==0.45.1
      - lxml==5.3.2
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - mmpt==0.0.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.4.2
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.0.5
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.8.0.74
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - portalocker==3.1.1
      - pose-format==0.9.0
      - protobuf==4.25.6
      - pycparser==2.22
      - pympi-ling==1.71
      - pyparsing==3.2.3
      - pysrt==1.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sign-language-segmentation==0.0.1
      - six==1.17.0
      - sounddevice==0.5.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - tqdm==4.67.1
      - transformers==4.51.2
      - triton==3.2.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - webvtt-py==0.4.6
prefix: /users/zifan/anaconda3/envs/sea
